default:
  seed: 0
  wrapper:
    pipeline: ['VirtualClutch']
    VirtualClutch: { start: 6 }
  task_name: block_picking
  embodied_name: PomdpEnv
  embodied:
    PomdpEnv:
      pybullet_gui: False
      obs_dict: True
      block_picking:
        something: True

no_clutch:
  wrapper.VirtualClutch.start: 0

no_obs_dict:
  embodied.PomdpEnv.obs_dict: False

gui:
  embodied.PomdpEnv.pybullet_gui: True