default:
  seed: 0
  wrapper:
    pipeline: ['VirtualClutch',"SymObs","GymRegularizer"]
    VirtualClutch: { start: 0 }
    SymObs: {skip: False}
    GymRegularizer: {
      obs_key: ['mask','depth', 'z_distance',  'image'],
    }
  task_name: block_pick
  embodied_name: PomdpEnv
  embodied:
    PomdpEnv:
      pybullet_gui: False

# no_clutch:
#   wrapper.VirtualClutch.start: 0

no_obs_dict:
  embodied.PomdpEnv.obs_dict: False
  wrapper.VirtualClutch: { start: 0 }

no_sym_obs:
  wrapper.SymObs.skip: true

gui:
  embodied.PomdpEnv.pybullet_gui: True

block_push:
  task_name: block_push

block_pull:
  task_name: block_pull

block_pick:
  task_name: block_pick



drawer_open:
  task_name: drawer_open


# other setting

origin_obs:
  wrapper.SymObs.skip: True