default:
  seed: 0
  wrapper:
    pipeline: ['VirtualClutch']
    VirtualClutch: { start: 6 }
  task_name: block_picking
  embodied_name: PomdpEnv
  embodied:
    PomdpEnv:
      pybullet_gui: False
      block_picking:
        something: True

no_clutch:
  wrapper.VirtualClutch.start: 0