default:
  seed: 0
  wrapper:
    pipeline: ['VirtualClutch',"SymObs"]
    VirtualClutch: { start: 6 }
    SymObs: {skip: False}
  task_name: block_pick
  embodied_name: PomdpEnv
  embodied:
    PomdpEnv:
      pybullet_gui: False
      obs_dict: True
      block_pick:
        something: True
      block_pull:
        something: True

no_clutch:
  wrapper.VirtualClutch.start: 0

no_obs_dict:
  embodied.PomdpEnv.obs_dict: False
  wrapper.VirtualClutch: { start: 0 }

no_sym_obs:
  wrapper.SymObs.skip: true

gui:
  embodied.PomdpEnv.pybullet_gui: True

block_pull:
  task_name: block_pull