default:
  seed: 0
  wrapper:
    pipeline: ['SymAug']
    SymAug: {sym_num: 4,}
  task_name: block_picking
  embodied_name: PomdpEnv
  embodied:
    PomdpEnv:
      pybullet_gui: False
      block_picking:
        something: True